### ISSUE TITLE
Question, not an issue

### ISSUE THREAD

**Issue by stagnoman** [Developer-Alexander/LargeCollections#1]
Alex, first of all, well done. It seems promising project. 
Honestly speaking, I didn't go through the code yet but I have a quick question: any way to develop SpatialDiskCache as concurrent dictionary? I assume it is not yet. 
Last, any way to get LargeCollections working under .net 4 instead of 2 only? How do I wrap it into a 4.6 net project?

Many Thks
Ciaoooo
LUCA

**Comment by Developer-Alexander** [comment]
Thanks! I am happy to hear that!
Making SpacialDiskCache concurrent would have a huge impact on performance. It would require a synchronization on disk.
But there are Methods fpr DiskCache and SpatialDiskCache to perform operations in parallel. This might result in some performance benefits.

I think the targets are limited by dependent lib Microsoft.Data.Sqlite.

**Comment by stagnoman** [comment]
Ciao Alex, ok thks.
On first point, u are right. Sequential db-writes are more performing.
About second: unfortunately, Microsoft.Data.Sqlite targets net2 or net6 only. I tried to pack it into net2 and then read it from 4 but it rejects it. I would need to find the trick to make it working, otherwise any project must be under 2 or net6 only. 
I will le t u know

**Comment by Developer-Alexander** [comment]
Maybe you can upgrade your project to .NET Framework 4.6.1. It should be able to deal with .NET Standard 2.0 libs.

**Comment by stagnoman** [comment]
thks, it works like a charm under net 4.6.1 microsoft.data.sqlite version 5.0.13
