### ISSUE TITLE
LargeArray CopyFrom ignores count

### ISSUE THREAD

**Issue by driderr** [Developer-Alexander/LargeCollections#2]
LargeArray CopyFrom will copy the whole source array despite count being smaller than the source array length due to this line:
` long bytesToCopyCount = Math.Min(currentSourceArray.LongLength - currentSourceItemIndex, currentTargetArray.LongLength - currentTargetItemIndex);`

I tested with a small source array to make sure it was actually being ignored.  Maybe the answer is to Math.Min the result of that line with "count - Currentcount" for bytesToCopyCount.

**Comment by Developer-Alexander** [comment]
Thanks for reporting the issue. Do you have an example?

**Comment by Developer-Alexander** [comment]
Should be fixed with v3.0.0.
